[book]
title = "PureScript: Jordan's Reference"
author = "Jordan Martinez, et al."
description = "An in-depth beginner-oriented guide to learning PureScript from Foundations-up."
lang = "en"
src = "./src"

[build]
build-dir = "docs"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
no-section-label = false
git-repository-url = "https://github.com/jordanmartinez/purescript-jordans-reference"
site-url = "https://jordanmartinez.github.io/purescript-jordans-reference-site/"

[output.html.search]
limit-results = 15
